# Generated by Django 4.2.4 on 2023-12-07 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiroz_B_IEI170_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reserva',
            table='django_reservas',
        ),
    ]
